#Конфигурация mySQL
spring:
  server:
    port: 8080
  database:
    host: localhost
    port: 5432
    dbname: search-system
    username: postgres
    password: 1234
    debug: true
  jpa:
    hibernate:
      ddl-auto: update

app-config:
  webInterfaceLogin: admin
  webInterfacePassword: admin
  prefix: search_
  agent: Mozilla/5.0 (Windows; U; WindowsNT 5.1; en-US; rv1.8.1.6) Gecko/20070725 Firefox/2.0.0.6
  webinterface: /admin
  site:
    - url: http://localhost:8080/test
      name: Test
    - url: https://dombulgakova.ru
      name: Dom Bulgakova
    - url: https://www.svetlovka.ru
      name: Библиотека


